//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7ADProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        public int AdjustmentId { get; set; }
        public Nullable<System.DateTime> AdjustmentDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public Nullable<System.DateTime> SupervisorAuthorizedDate { get; set; }
        public Nullable<int> HeadId { get; set; }
        public Nullable<System.DateTime> HeadAuthorizedDate { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }

    }
}
