//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7ADProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int DeliveryId { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
