//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7ADProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementList
    {
        public DisbursementList()
        {
            this.DisbursementDetails = new HashSet<DisbursementDetail>();
        }
    
        public int DisbursementListId { get; set; }
        public Nullable<int> RetrievalId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> OrderedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> CollectionPointId { get; set; }
        public string Status { get; set; }
    
        public virtual CollectionPoint CollectionPoint { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<DisbursementDetail> DisbursementDetails { get; set; }
        public virtual Retrieval Retrieval { get; set; }
    }
}
