//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7ADProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permission()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int PermissionId { get; set; }
        public Nullable<bool> ApproveRequisition { get; set; }
        public Nullable<bool> ChangeCollectionPoint { get; set; }
        public Nullable<bool> ViewRequisition { get; set; }
        public Nullable<bool> MakeRequisition { get; set; }
        public Nullable<bool> DelegateRole { get; set; }
        public Nullable<bool> ViewCollectionDetails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
